name: test

on:
  - pull
  - push

jobs:
  runs-on: windows-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Install Platform
      run: |
        arduino-cli core update-index https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        arduino-cli core install esp32:esp32

    #- name: Compile Sketch
      #run: arduino-cli compile --fqbn esp32:esp32:esp32 ./blink
